[package]
name = "engarde_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
serde = "1.0.199"
serde-aux = "4.5.0"
serde_json = "1.0.116"
serde_with = "3.8.1"
